#Makefile
#Used to complie file
#Command to run make file 'make -f Makefile'

CC      = gcc
CFLAGS  = -g
RM      = rm -f


default: all

all: main

main: main.c
    $(CC) $(CFLAGS) main.c

clean:
      rm -rf *o main
